services:
  # 1. The React Dashboard
  frontend:
    build: ./eduflow-frontend
    ports:
      - "3000:3000"
    volumes:
      # This line links your Windows folder directly to the Docker container
      - ./eduflow-frontend:/app
      # These lines protect the container's internal installed packages
      - /app/node_modules
      - /app/.next
    depends_on:
      - core-api

  # 2. The Database Manager
  core-api:
    build: ./core_api
    ports:
      - "4000:4000"
    env_file:
      - ./core_api/.env
    volumes:
      # Links your Python code so backend changes update instantly too!
      - ./core_api:/app 
    depends_on:
      - ml-engine

  # 3. The AI Brain
  ml-engine:
    build: ./ml_core
    ports:
      - "8000:8000"
    volumes:
      - ./ml_core:/app