services:
  
  core-api:
    build: ./core_api
    ports:
      - "4000:4000"
    env_file:
      - ./core_api/.env 
    depends_on:
      - ml-engine

  
  ml-engine:
    build: ./ml_core
    ports:
      - "8000:8000"